### ISSUE TITLE
There was an error writing the tags

### ISSUE THREAD

**Issue by samcro1967** [mdhiggins/sickbeard_mp4_automator#1419] opened 2021-02-22 22:00 UTC
I am seeing an intermittent issue when trying to update the tags for video files during the conversion process.  I'd say it happens on about 5% of the files.  If I reencode the file, it seems to work, but I just had one I have tried twice and it is not working.  Below is what I see in the logs.

[Logs](https://pastebin.com/nU00FK5b)

**Comment by mdhiggins** [comment] 2021-02-22 22:16
Is it doing this consistently for this file? I'm not able to reproduce it using the same filename and tagging ID on a test file. Based on the logs it looks like you're using Spanish as your tag language so I tried that as well without any problems

![image](https://user-images.githubusercontent.com/3608298/108777121-52ec5780-7531-11eb-8adc-7a647d3215ad.png)

This error can sometimes be from a malformed mp4 container or absent metadata. Try running the conversion again with debug level logging and let me know if it still fails and please post the logs

https://github.com/mdhiggins/sickbeard_mp4_automator/wiki/Debug-Level-Logging

Additionally, it might be worthwhile to try a new FFMPEG build in case there's a problem with the conversion that's corrupting the mp4 container and see if that resolves the issue.

**Comment by samcro1967** [comment] 2021-02-22 22:34
I got it twice on this file.  That is the first time I have ever had it happen twice on the same file.  I had updated ffmpeg on Jan. 9th this year, but went ahead and updated it again just now and set the logger_fileHandler log level to debug.  Of course it worked the third time I converted it.  I have a bunch more to convert the next few days so if I see it again, I will post the debug logs.  Hopefully the ffmpeg update resolved it.

**Comment by samcro1967** [comment] 2021-02-23 01:52
Had another occurrence with a different file.

[Logs](https://pastebin.com/kijabPnR)

[autoProcess.ini](https://pastebin.com/Bij2hf7Z)

**Comment by mdhiggins** [comment] 2021-02-23 17:08
Not having any issues here either able to write the tags using an exact copy of your autoProcess.ini and the same command for manual.py

I'm thinking something specific to your setup is corrupting the mp4 files

Things I would try

- double check your mutagen version, this is the program that handles the tagging and is throwing the error using `pip show mutagen`. Current version and the one on my system that's working is 1.45.1. If you're below that version I would update using `pip install --upgrade mutagen`
- update to a new FFmpeg build/binary, if you're compiling from source consider trying to a premade binary as well
- make sure no other programs are trying to read/write the files at the same time. Some programs that automatically scan directories for media like plex or other various media managers may be trying to write things to the file at the same time

Also always a good idea to do a fresh pull and get a clean version of the script and clear out the existing directory with the exception of your autoProcess.ini file

Make sure you don't have things like a mutagen folder in the script root directory (very old versions of the script used to come packaged with a mutagen directory before it was available on pip). This can be easily avoided by deleting the script and doing a clean download from GitHub.

I doubt this is an issue with the source files since FFmpeg is creating new files on both the conversions you linked but if you wanted to send me a sample source file to try on my end I can take a look

Beyond that, you'll probably have to go to the mutagen GitHub and ask for help

**Comment by samcro1967** [comment] 2021-02-23 17:35
I had problems with 5 files in a row.  I updated mutagen from 1.40 to 1.45.1, reran, and all 5 converted and tagged just fine.  That seems to have solved it.

**Comment by mdhiggins** [comment] 2021-02-23 18:06
Excellent, thanks for following up with the solution

**Comment by samcro1967** [comment] 2021-02-24 16:55
I got the same error again today.  I pulled the latest SMA and tried again with the same results.  Any other ideas?

[Logs](https://pastebin.com/pBvVDx4p)

**Comment by mdhiggins** [comment] 2021-02-24 17:37
FFMpeg binaries

**Comment by samcro1967** [comment] 2021-02-24 20:02
I used ffmpeg-N-101196-gf569ac4ce0-win64-shared from https://github.com/BtbN/FFmpeg-Builds/releases.  What source would you recommend or do you use?

**Comment by mdhiggins** [comment] 2021-02-24 20:07
https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2021-02-24-12-33/ffmpeg-n4.3.2-win64-lgpl-shared-4.3.zip

**Comment by samcro1967** [comment] 2021-02-24 20:24
Same behavior with that version as well.  I would think it is an issue with the source file, but eventually it works if I do it a few times.  I am using Handbrake to create an m4v file from a DVD with the Fast 1908p30 preset.  MP4 File Conversion is set to auto and it creates an m4v file.  I am running the latest version of Handbrake.  I don't remember when I last updated it.  This issue has been going on the past month or so maybe.  Prior to that, never saw this problem.

**Comment by mdhiggins** [comment] 2021-02-24 21:00
That's a relatively strange workflow. Why are you converting with handbrake only to then convert again with FFMpeg and not doing everything in FFMpeg natively￼?

You could also potentially tag without the secondary FFMpeg conversion to save an extra step If you adjusted your autoprocess.ini settings.￼

Regardless, I don't think either of these things will help the underlying issue. At this point I have no further suggestions￼ and suspect this is some anomaly with your system or environment causing file corruption.￼ You could potential head over to the mutagen repository and inquire if they have any suggestions as this is ultimately an underlying problem with that software that is non-specific to SMA

It would also be interesting to see if cutting out handbrake or the secondary FFMpeg conversion step makes any difference though I would speculate that it would not, But there is certainly no reason to do both steps￼. If you have the means to test these same files on another system￼ that are failing to see if you can reproduce it that might be helpful as well.￼

**Comment by samcro1967** [comment] 2021-02-24 21:12
Agreed a strange workflow.  Only using Handbrake due to its simplicity.  Easiest way I have found to get from a DVD to a file.

I only re-encode so I am not opening up the autoProcess.ini to file to turn it on and off depending on whether I am encoding an m4v file or an mkv file.  It does not take very long to reencode.  Really using SMA in this instance just to tag the file.

I will try it with encoding off as well as move it off the NAS to a local drive just to see if that has any impact.  I checked the NAS and backups and AV are not running and it does not show the file in use when the job starts.

If that doesn't work, I will move it to another machine, install SMA there, and try it to see if the problem follows it.

Appreciate your persistence.  Totally baffled by this one.

**Comment by mdhiggins** [comment] 2021-02-24 21:15
You could still keep using handbrake and have the script skip the FFMPEG rewrap which I guess in theory might save you some time and hard drive write cycles. Might be worth trying to see if that fixes the issue. Just have your input and output extension be the same and turn off process-same-extensions. It'll still tag

**Comment by samcro1967** [comment] 2021-02-24 21:44
The other reason I use SMA to reencode is to set the max-bitrate to 5000.  Playing files remotely after only converting with Handbrake I sometimes see the bandwidth spike to 100 Mbps and the video lags.  Using SMA and setting the max bit rate keeps the bandwidth between 10 and 15 Mbps and eliminates lags.  There is probably a away to do that in Handbrake.  I just couldn't find it quickly and never looked too hard since SMA was taking care of it.

**Comment by mdhiggins** [comment] 2021-02-24 22:00
Yeah I would definitely look into doing that in handbrake then since doing a video conversion of another conversion is gonna waste a lot of CPU time and generally reduce your quality. It would still be interesting to see if that double-conversion is playing a role here

Try turning on the `bypass-if-copying-all` option and make your input/output extensions match with `process-same-extensions` turned on

This will analyze the file, allow FFMPEG bypass if no conversion needs to take place (like if your max bitrate is <5000 for example), but still convert in situations where it breaks the rules of one of your other settings (bitrate >5000)

**Comment by samcro1967** [comment] 2021-02-24 23:27
Setting bypass-if-copying-all to True did not have an effect.  I also tried it from the local drive instead of a network drive and got the same error.  I set it up on a different machine and got the same error.  I will work on getting handbrake to encode directly to mp4 and set a max bit rate tomorrow.  It seems like there is an issues with Handbrake and how it is creating the encoded file.

**Comment by mdhiggins** [comment] 2021-02-25 05:33
I wonder if handbrake is structuring the metadata in a way that isn't compatible and FFMPEG is copying it forward. Try adding 

-map_metadata, -1

To your post-opts in autoProcess.ini

Not 100% that will work as a post-opt but if it does that should strip any metadata from the source file before FFMpeg wraps it in the container. For this to work the previous bypass options should be turned back off so that FFMpeg is forced to run. 

Also if you have any logs from those earlier attempts with the option changes I'll take a look

Can you send me one of the files you made with handbrake that's failing? I can do some testing

**Comment by samcro1967** [comment] 2021-02-26 14:10
I have done 20+ in the past 24 hours without an issue.  I forced HandBrake to convert to an MP4 file and it seems to be working consistently for the moment.  I have "process-same-extensions = True" and "bypass-if-copying-all = True" in autoProcess.ini.  "postopts" is empty.

I updated HandBrake to 1.3.3 back on 8/8/20.  I didn't think this has been going on that long, but it is possible.  I saw a much higher rate of failure over the past week than I had the several weeks before.  Seems to me it has an issue when left to auto for the file extension and it creates and m4v file.

Here are some logs from earlier attempts if you still wanted to look through them.
[Logs](https://pastebin.com/cAYrj287)

**Comment by mdhiggins** [comment] 2021-02-27 18:28
So the logs here basically show that bypassing the second conversion wasn't helping which leads me back to it being something abnormal with handbrake. Glad you got it fixed. 

Could you still potentially send me a source file that was giving you the problem for some testing?

**Comment by samcro1967** [comment] 2021-02-28 16:48
I sent you a link to a test file.  Let me know once you have it so I can remove it.

**Comment by mdhiggins** [comment] 2021-02-28 21:09
Got the file, you can take it down

**Comment by mdhiggins** [comment] 2021-03-01 16:45
Still not able to reproduce this, ran the conversion 10+ times and worked every time. Either way seems your issue is resolved and it was probably something to do with handbrake so closing this out

**Closed by mdhiggins** 2021-03-01 16:45 UTC

**Comment by samcro1967** [comment] 2021-03-01 17:30
Agreed.  I think there are 2 separate issues which are linked.  One is that HandBrake is creating files that creates an issue with tagging.  The second is something with my local config.  The file you tested fails for me consistently where it works for you consistently.  I can work around this by adjusting the HandBrake config to avoid the issue in the future.

**Comment by mdhiggins** [comment] 2021-03-02 19:24
Out of curiosity, on the files that consistently failed, did the `post-opts = -map_metadata, -1` help at all?

**Comment by samcro1967** [comment] 2021-03-02 19:38
No, it had no effect.  I just tested it again.  I also tried to run manual.py from inside radarr-sma to test it from another machine/OS, but it looks like not all of the prereqs are there.  It errs out looking to import guessit.

**Comment by mdhiggins** [comment] 2021-03-02 19:46
The docker containers also use a virtual python environment that you need to execute the script from, that virtual environment contains all the requirements

`/usr/local/sma/venv/bin/python3 /usr/local/sma/manual.py` from inside the container should do the trick

**Comment by mdhiggins** [comment] 2021-03-02 20:10
I also added a new `strip-metadata` option to the autoProcess.ini `[Metadata]` section that should try and wipe any existing metadata from the source file during an FFMPEG conversion that FFMPEG might attempt to carry over

If you have time see if that fixes the error too (and toss some logs my way with this option enabled)

**Comment by samcro1967** [comment] 2021-03-02 20:12
I was able to run it in the radarr-sma container, but still failed.  Not sure the logs show anything different, but they are here.

[Logs](https://pastebin.com/QXMGuc3G)

**Comment by mdhiggins** [comment] 2021-03-02 20:15
Looks like the FFMPEG conversion isn't taking place

```
Input and output extensions match, the file appears to copying all streams, and is not reducing the number of streams, enable force-convert to override [bypass-if-copying-all] [force-convert: False].
Bypassing conversion and setting outputfile to inputfile.
```

I would turn off the `bypass-if-copying-all` and remove `-map_metadata, -1` from postopts if its still there, and try with the new `strip-metadata` option set to true. That will include the metadata wipe right after your inputfile specification in the FFMPEG command and hopefully provide some layer of protection from files that would cause this crash by recreating the mp4 container with clean atoms

**Comment by mdhiggins** [comment] 2021-03-02 20:16
You can run `git -C /usr/local/sma pull origin master` from inside the container to update quickly

**Comment by samcro1967** [comment] 2021-03-02 20:24
It worked that time from inside radar-sma.

Here are the logs from that run
[Logs](https://pastebin.com/USuCzSQW)

**Settings**
git -C /usr/local/sma pull origin master
process-same-extensions = True
bypass-if-copying-all = False
postopts = <blank>
strip-metadata = True

**Comment by mdhiggins** [comment] 2021-03-02 20:27
Awesome

So my best guess here is that whatever old version of handbrake you were using was doing something weird when writing the moov atoms/headers when it was creating the file, and FFMPEG was just copying that data over during its conversion so it was persisting despite the file being recreated. That abnormality was then crashing mutagen when it went to write the tags

This change just wipes all that when the file is rewrapped by FFMPEG and then everything works as expected. Good to have that new `strip-metadata` option though to prevent this in the future since its certainly possible other files may have bad metadata from any source

Thanks for the extra effort in testing this even though it had resolved with updating handbrake

**Comment by samcro1967** [comment] 2021-03-02 20:49
Make sense to me.  No problem helping troubleshoot.

It is the latest version of Handbrake 1.3.3 (2020061300) that is causing the problem.  The fix in Handbrake was to change Settings | Output File | MP4 File Extension from Auto to Always use MP4.  If left to auto, it was creating M4V files.  That seems to then create mp4's that worked every time and don't experience this problem.
