### ISSUE TITLE
Subtitle is not moved from output-extension folder

### ISSUE THREAD

**Issue by ClankJake** [mdhiggins/sickbeard_mp4_automator#1512] opened 2022-01-04 21:37 UTC
When I define a temporary save location in the output-extension option but when the media process ends, another save location moves. The subtitle not moved along with the file getting separated is there any solution for that?

Edit: I'm using manual.py to do the process

**Comment by mdhiggins** [comment] 2022-01-04 22:06
Could you post your current autoProcess configuration as well as a sample set of logs for a conversion that's exhibiting the behavior

**Comment by mdhiggins** [comment] 2022-01-04 22:24
Actually I was able to reproduce this without that info and should have it fixed in the latest update

ba94986dce19e4ba4fcff61631e942c92f724bf1

See if that works for you

**Comment by ClankJake** [comment] 2022-01-04 22:30
Thanks. But I won't be able to see this until tomorrow.

**Comment by mdhiggins** [comment] 2022-01-04 23:13
Alright well seems to be fixed in my tests so I'll close this out but reopen if there's any issues.

**Closed by mdhiggins** 2022-01-04 23:13 UTC
