### ISSUE TITLE
Provide Image Repo XML file for Unraid users to easily add sma docker images

### ISSUE THREAD

**Issue by kmr2319** [mdhiggins/sickbeard_mp4_automator#1119] opened 2020-02-01 21:35 UTC
Opening this issue in the main repo since I think it would make sense to have this in the main repo to get some extra visibility on your dockers...

Plex provides one for their official docker:
https://github.com/plexinc/pms-docker/blob/master/plex-unRAID.xml

LinuxServer.io has a directory of them for their images:
https://github.com/linuxserver/docker-templates/tree/master/linuxserver.io

This makes it easy in Unraid to just select the template, fill out a few options and pull...

I'll see if I can get a PR over to you in the next day or so with suggestions.

**Comment by mdhiggins** [comment] 2020-02-03 14:27
Would be open to a PR; I don't have an unraid setup to test on

**Comment by gtholder1** [comment] 2020-03-01 19:49
Hi, has there been any traction on this?  I love your scripts, but i just switched my server over to Unraid from FreeNas and I am completely lost in the world of dockers.  I get along "ok" with the templates to fill in, but trying to install the dockers for radarr-sma and sonarr-sma from docker hub has me pretty confused.

Appreciate everyone's hard work!

**Comment by mdhiggins** [comment] 2020-03-01 21:37
I don’t have any unraid hardware and no familiarity with this. Happy to take a pull request but it’s not something I’m actively working on. The docker containers aren’t hard to get up and running though.

**Comment by gtholder1** [comment] 2020-03-01 22:01
My problem is that i'm still learning unraid and it's docker configuration templates, and I don't know what info needs to be added via the template (paths, variables etc.) for the pull/build. 

Still, Ive been using your scripts for 4+ years.... I really appreciate your time you have devoted. Hopefully someday a walkthrough will be posted somewhere.

**Comment by kmr2319** [comment] 2020-03-01 22:05
I thought I had time when I first opened this issue... Then that changed... :cry: 

I'm going to try to mess with it right now... :smile: 

I don't know if I'll get a PR in today, but hopefully soon.

**Comment by gtholder1** [comment] 2020-03-01 22:19
kmr, I appreciate you taking the time to do it.  If i am not misunderstanding how it works, the xml that you are making will be added to the docker setup so that in unraid I just have to fill in the various variables and I should be able to make Sonarr-sma and Radarr-sma work?

**Comment by kmr2319** [comment] 2020-03-01 22:35
@gtholder1 Basically I'm creating the .xml file that unraid will read in when the URL is added to  "template repositories" in unraid. This is now LS.io and Plex handle it:
![screenshot-24bde27a](https://user-images.githubusercontent.com/17013046/75635260-a65bec00-5be2-11ea-82eb-a04be2e736b2.jpg)

Just picture an "https://github.com/mdhiggins/sickbeard_mp4_automator/unraid" URL in the above screen shot... 

Then yes, when clicking on add container in unraid, you'd select sonarr-sma and radarr-sma and fill out the form accordingly.

At least, in theory... :laughing:

**Comment by gtholder1** [comment] 2020-03-01 22:43
Got it. so once added to the templae repositories it becomes available in the template dropdown on the create container page, then i would select either sonarr-sma or radarr-sma?

**Comment by kmr2319** [comment] 2020-03-01 23:03
That's one user friendly way for it to work and is plan that I'm working on...

The other way is to add a community application (accessible via the community applications plugin with unraid) and that would pull down the template accordingly. There are a lot like that; one example that I use is tdarr_aio.

Being as that is all unraid specific and the maintainer of the *-sma dockers (@mdhiggins ) doesn't have an unraid setup, I figured using the direct xml templates would be the most acceptable thing to do without causing him much headache.

I'm sure that there are other ways of dealing with docker on unraid - but that conversation is best left in the unraid forums.

**Comment by RandomNinjaAtk** [comment] 2020-03-04 20:17
I could create the xml and host it as part of my repo if your okay with that? @mdhiggins

**Comment by kmr2319** [comment] 2020-03-04 20:24
@RandomNinjaAtk So I already have the script created and ran some quick tests against it. Works well:
https://github.com/kmr2319/sickbeard_mp4_automator/blob/master/unraid/radarr-sma.xml

However my ultimately (self-serving) goal was to get it with the nvidia FFMPEG build included. I haven't yet figured out how (if there is even away) to pass in the tag args required for docker to pull the right images via the unraid xml templates.

But there's nothing really stopping me with submitting the PR for the default *arr-sma dockers...

**Comment by mdhiggins** [comment] 2020-03-05 05:43
I'm happy to merge something back into the main branches if you wanna submit a pull request

**Comment by RandomNinjaAtk** [comment] 2020-03-11 22:26
@kmr2319 

I posted a version of sonarr-sma to the unraid app store that has the nvidia ffmpeg build in it. I have not tested it, as I do not have nvidia, but the vaapi accelerated one works and also the regular version. Search for it on unraid as sonarr-sma

It is a slightly modified version of the one you make @mdhiggins 

To enable HW acceleration, its not as simple to just push a xml here, and to get it added to the "store" takes some additional setup, so I'm not sure it made sense to write a pull request here, unless you wanted to create the additional branches to support the HW acceleration

**Comment by mdhiggins** [comment] 2020-03-11 22:58
I like your bash script that does the sim linking. I've struggled to determine what the best way to handle some of the directory structure was

**Comment by RandomNinjaAtk** [comment] 2020-03-11 23:14
Yeah, I did that to try and simplify it, I'm also already on the Unraid app store, so its easy to publish. The only real major reason I had to create my own based on yours was because it needed to use different ffmpeg builds for hw acceleration. And unraid is not setup to build locally, but pull directly from docker hub, so it already has to be configured that way. 

I also considered making the settings fully customizable just using env variables, but the problem is, I would have to constantly make sure it gets updated as you update the script with new features. So I chose not to do it.

**Comment by gtholder1** [comment] 2020-03-12 02:59
Ninja, is the version you put on the unraid store usable if you don't have nvidia hardware acceleration?

**Comment by RandomNinjaAtk** [comment] 2020-03-12 09:17
@gtholder1 yes it is, just use the latest tag.

**Comment by mdhiggins** [comment] 2020-03-12 14:49
@RandomNinjaAtk quick heads up in an effort to have better respect for linux file structure the log file is going to be moved to /var/log/sma.log instead of into a subdir. I also included an environment variable named "SMA_LOGLOCAL" that if set to true will have the script log into the config directory of the script folder like on windows which can be useful if mounting that folder for docker containers
By default now windows will use the /config folder for log storage as well

1d4270395cda58cd30a56b338684e289857da5e2

Rebuilding the base containers now to reflect that change

**Comment by RandomNinjaAtk** [comment] 2020-03-12 16:42
@mdhiggins I noticed and have already started pushing the changes. Thx for the heads up!

**Comment by RandomNinjaAtk** [comment] 2020-03-12 21:41
@mdhiggins FYI, I have a version for radarr currently being built and added to unraid. This request can probably be closed because it should be resolved...

https://github.com/RandomNinjaAtk/docker-radarr-sma

**Comment by mdhiggins** [comment] 2020-03-13 01:48
Gonna close this then, if you have any desire to make a small wiki page and add those links for unraid feel free

**Closed by mdhiggins** 2020-03-13 01:48 UTC
Labels: docker, unraid

**Comment by RandomNinjaAtk** [comment] 2020-03-13 02:06
Sure, I'll do that when I get a chance.

**Comment by RandomNinjaAtk** [comment] 2020-03-13 02:13
@mdhiggins FYI, It doesn't look like its possible for me to update the wiki, I don't think you have the permissions open for anyone to be able to edit it.

**Comment by mdhiggins** [comment] 2020-03-13 02:21
Hm whoops, well if you post it here I'll make it into a wiki page then

**Comment by mdhiggins** [comment] 2020-03-15 15:44
@RandomNinjaAtk 
Another hopefully good change I wanted to update you on in case you need to update your scripts
Migrated logging.ini to the config folder (now that can be permanently customized)
Ditched the environment variable to override log path (since that can already be done via logging.ini)
Logging.ini not included in repo anymore, sample file included
Sample files moved to ./setup

Wiki for logging
https://github.com/mdhiggins/sickbeard_mp4_automator/wiki/Logging

So now you can mount the config folder and have access to logging and basic configuration
