### ISSUE TITLE
Metadata based on film language?

### ISSUE THREAD

**Issue by LunaticZorr** [mdhiggins/sickbeard_mp4_automator#1369] opened 2020-11-29 14:29 UTC
Hi,

I'm looking to implement this to my download workflow, but I download movies in multiple languages (mostly English, Spanish and some German), and would like to know if when running this and add metadata from TMDB, it add the metadata in the language the movie is. For example, download Matrix in English, add metadata from TMDB in English; download Matrix in Spanish, add metadata from TMDB in Spanish.

So that when added to Plex, the name, description and other metadata is displayed in the language the movie is in.

Thanks!

**Comment by mdhiggins** [comment] 2020-11-29 21:03
ffc65fd77368f262433764e6aea6d11def7d30f7

Try this update, set the tag-language in settings to nothing for it to try auto-detect

Determining the language isn't 100% straightforward (first track?, most channels? what if multiple audio tracks in multiple languages?) so I decided to analyze the output file to be generated and use whatever language the 'default' audio track will be as the tag language. This way the tag language respects what the user prioritizes as the default audio language based on channels, dispositions, etc

Having tag-language set will always default to that language however and will not try to auto detect

**Comment by mdhiggins** [comment] 2020-12-02 03:23
Closing for now, let me know if there are issues with this new feature

**Comment by LunaticZorr** [comment] 2020-12-04 00:53
Hi!

Sorry for the late response. I've tried it running the manual.py but it doesn't seem to work. 

The file has the following audio channels:

![image](https://user-images.githubusercontent.com/19307263/101107511-59ba9c80-35ca-11eb-9a9c-371eff3805f1.png)

I've changed the config file to the following (leaving the `tag-language` empty:

```
[Metadata]
relocate-moov = True
full-path-guess = True
tag = True
tag-language = 
download-artwork = poster
sanitize-disposition = 
```
And when I check the metadata of the file, it is in English:

```
Media Language Code             : eng
...truncated...
Cover Art                       : (Binary data 952838 bytes, use -b option to extract)
HD Video                        : Yes
Media Type                      : Movie
Description                     : Time is the enemy
Long Description                : At the height of the First World War, two young British soldiers must cross enemy territory and deliver a message that will stop a deadly attack on hundreds of soldiers.
```

I thought the issue may be that the language tag of the audio channel being `spa` is not recognized, so I've then tried setting the `tag-language` manually to `es-ES` which is the language tag used in TMDB:

```
[Metadata]
relocate-moov = True
full-path-guess = True
tag = True
tag-language = es-ES
download-artwork = poster
sanitize-disposition = 
```

But the result was the same. The metadata gets set in English.

**Comment by mdhiggins** [comment] 2020-12-04 00:57
es-ES is not a valid language code, it needs to be the 2 or 3 character language code, so that's probably why the manual option isn't working

Can you post the full conversion logs for this file with DEBUG level logging enabled?

https://github.com/mdhiggins/sickbeard_mp4_automator/wiki/Debug-Level-Logging

**Comment by LunaticZorr** [comment] 2020-12-04 01:11
> 
> 
> es-ES is not a valid language code, it needs to be the 2 or 3 character language code, so that's probably why the manual option isn't working

Ah! That was it, yes. I've set the language tag to `es` and that worked fine, including the metadata in the correct language!

I guess the auto-detect language will not work in my case, since the audio channel for Spanish is called `spa` instead of `es`.

**Comment by mdhiggins** [comment] 2020-12-04 01:12
spa should work too, there's a whole function that processes the language codes and converts between 3 and 2 character codes. That's why I want to see some logs

**Comment by mdhiggins** [comment] 2020-12-04 01:13
Or alternatively send me the file in question

**Comment by LunaticZorr** [comment] 2020-12-04 17:29
> 
> 
> spa should work too, there's a whole function that processes the language codes and converts between 3 and 2 character codes. That's why I want to see some logs

Ah! Ok :) 

I've attached the SMA.LOG file, and below is my `autoconfig` file:


[sma.log](https://github.com/mdhiggins/sickbeard_mp4_automator/files/5644315/sma.log)


```
[Converter]
ffmpeg = ffmpeg.exe
ffprobe = ffprobe.exe
threads = 0
hwaccels = dxva2, cuvid, qsv, d3d11va, vaapi
hwaccel-decoders = h264_cuvid, mjpeg_cuvid, mpeg1_cuvid, mpeg2_cuvid, mpeg4_cuvid, vc1_cuvid, hevc_qsv, h264_qsv, hevc_vaapi, h264_vaapi
hwdevices = vaapi:/dev/dri/renderD128
hwaccel-output-format = vaapi:vaapi
output-directory = 
output-format = mp4
output-extension = mp4
temp-extension = 
minimum-size = 0
ignored-extensions = nfo, ds_store
copy-to = 
move-to = 
delete-original = True
sort-streams = True
process-same-extensions = False
force-convert = False
post-process = False
wait-post-process = False
detailed-progress = False
preopts = 
postopts = 
bypass-if-copying-all = False

[Permissions]
chmod = 0644
uid = -1
gid = -1

[Metadata]
relocate-moov = True
full-path-guess = True
tag = True
tag-language = 
download-artwork = poster
sanitize-disposition = 

[Video]
codec = h264, x264
max-bitrate = 0
crf = -1
crf-profiles = 
preset = 
codec-parameters = 
dynamic-parameters = False
max-width = 0
profile = 
max-level = 0.0
pix-fmt = 
filter = 
force-filter = False

[HDR]
pix-fmt = 
space = bt2020nc
transfer = smpte2084
primaries = bt2020
preset = 
codec-parameters = 
filter = 
force-filter = False

[Audio]
codec = ac3
languages = 
default-language = 
first-stream-of-language = False
allow-language-relax = True
channel-bitrate = 128
max-bitrate = 0
max-channels = 0
prefer-more-channels = True
default-more-channels = True
filter = 
force-filter = False
sample-rates = 
copy-original = False
aac-adtstoasc = False
ignore-truehd = mp4, m4v
ignored-dispositions = 
unique-dispositions = False

[Universal Audio]
codec = aac
channel-bitrate = 128
first-stream-only = False
move-after = False
filter = 
force-filter = False

[Subtitle]
codec = mov_text
codec-image-based = 
languages = 
default-language = 
first-stream-of-language = False
encoding = 
burn-subtitles = False
burn-dispositions = 
download-subs = False
download-hearing-impaired-subs = False
download-providers = 
embed-subs = True
embed-image-subs = False
embed-only-internal-subs = False
filename-dispositions = forced
ignore-embedded-subs = False
ignored-dispositions = 
unique-dispositions = False
attachment-codec = 

[Sonarr]
host = localhost
port = 8989
apikey = 
ssl = False
webroot = 
force-rename = False

[Radarr]
host = localhost
port = 7878
apikey = 
ssl = False
webroot = 
force-rename = False

[Sickbeard]
host = localhost
port = 8081
ssl = False
apikey = 
webroot = 
username = 
password = 

[Sickrage]
host = localhost
port = 8081
ssl = False
apikey = 
webroot = 
username = 
password = 

[CouchPotato]
host = localhost
port = 5050
username = 
password = 
apikey = 
delay = 65
method = renamer
delete-failed = False
ssl = False
webroot = 

[SABNZBD]
convert = True
sickbeard-category = sickbeard
sickrage-category = sickrage
couchpotato-category = couchpotato
sonarr-category = sonarr
radarr-category = radarr
bypass-category = bypass
output-directory = 
path-mapping = 

[Deluge]
couchpotato-label = couchpotato
sickbeard-label = sickbeard
sickrage-label = sickrage
sonarr-label = sonarr
radarr-label = radarr
bypass-label = bypass
convert = True
host = localhost
port = 58846
username = 
password = 
output-directory = 
remove = False
path-mapping = 

[qBittorrent]
couchpotato-label = couchpotato
sickbeard-label = sickbeard
sickrage-label = sickrage
sonarr-label = sonarr
radarr-label = radarr
bypass-label = bypass
convert = True
action-before = 
action-after = 
host = localhost
port = 8080
ssl = False
username = 
password = 
output-directory = 
path-mapping = 

[uTorrent]
couchpotato-label = couchpotato
sickbeard-label = sickbeard
sickrage-label = sickrage
sonarr-label = sonarr
radarr-label = radarr
bypass-label = bypass
convert = True
webui = False
action-before = 
action-after = 
host = localhost
ssl = False
port = 8080
username = 
password = 
output-directory = 
path-mapping = 

[Plex]
host = localhost
port = 32400
refresh = False
token = 


```

**Comment by mdhiggins** [comment] 2020-12-04 18:30
I need to be DEBUG level logging or it won't be helpful, see the attached link from earlier

https://github.com/mdhiggins/sickbeard_mp4_automator/wiki/Debug-Level-Logging

**Comment by LunaticZorr** [comment] 2020-12-04 21:24
Hi @mdhiggins

Sorry for that, I set the wrong parameter to DEBUG. Here's a new log file with the DEBUG set correctly. Config file has not changed.

[sma.log.log](https://github.com/mdhiggins/sickbeard_mp4_automator/files/5645554/sma.log.log)

**Comment by mdhiggins** [comment] 2020-12-04 22:43
So this isn't helpful either, the important part of the log is cut off you only included the very end, need the full conversion from start to finish
May need to increase your max log file size or include the .1 / .2 files etc

**Comment by LunaticZorr** [comment] 2020-12-05 00:24
Ok, there you go. Not sure what happened there. I've copied the content of the log file into a txt file and uploaded that.

[sma-log.txt](https://github.com/mdhiggins/sickbeard_mp4_automator/files/5646166/sma-log.txt)

**Comment by mdhiggins** [comment] 2020-12-06 02:20
It almost looks like your tag language is still set, can you double check that?

I also pushed an update here 723f866aafeb1dbf7f5a004b7c1326e95e977011 that adds some more debugging logs related to language to try and see where this is messing up

**Comment by mdhiggins** [comment] 2020-12-07 20:11
Still unable to reproduce this

**Comment by LunaticZorr** [comment] 2020-12-09 11:30
Hi,

I've done a new test using the latest version, and this time the Metadata has been added in the correct language. Attached the log file

[sma.log](https://github.com/mdhiggins/sickbeard_mp4_automator/files/5665531/sma.log)

I've noticed that now when running the manual conversion, it does the full conversion first, and then asks me to choose a source for the metadata (TMDB, IMDB, etc) and give the movie ID. Before it usually asked me for that before the conversion.

Also, is there any way of detecting and searching the movie on TMDB automatically? So that I don't have to go into TMDB, search for the movie and provide the ID myself every time? I guess it's the `guessInfo` part, which seems to fail

```
2020-12-09 11:18:01 - MANUAL - ERROR - Unable to guess movie information
Traceback (most recent call last):
  File "C:\Users\Kevin\Downloads\sickbeard_mp4_automator-master\manual.py", line 166, in guessInfo
    return tvInfo(guess, tmdbid=tmdbid, tvdbid=tvdbid, imdbid=imdbid, season=season, episode=episode, language=language, original=original)
  File "C:\Users\Kevin\Downloads\sickbeard_mp4_automator-master\manual.py", line 198, in tvInfo
    season = season or guessData["season"]
KeyError: 'season'
```

**Comment by LunaticZorr** [comment] 2020-12-09 16:04
Ok, about detecting and searching the movie on TMDB automatically, it does actually do that.
The problem is that movies in Spanish all when downloaded all come with a bloated title, eg:

```
Los nuevos mutantes M1080.pctmix.com
Los nuevos mutantes [MicroHD 1080p][AC3 5.1-DTS 5.1-Castellano-AC3 5.1 Ingles+Subs][ES-EN]
```

And it fails due to that. I've tried changing it to

```
Los nuevos mutantes
```

And that worked fine.

**Comment by LunaticZorr** [comment] 2020-12-09 16:09
Is there any way to not copy the original audio tracks?

My config is

```
[Audio]
codec = ac3
languages = 
default-language = 
first-stream-of-language = False
allow-language-relax = True
channel-bitrate = 128
max-bitrate = 0
max-channels = 0
prefer-more-channels = True
default-more-channels = True
filter = 
force-filter = False
sample-rates = 
copy-original = False
aac-adtstoasc = False
ignore-truehd = mp4, m4v
ignored-dispositions = 
unique-dispositions = False

[Universal Audio]
codec = aac
channel-bitrate = 128
first-stream-only = False
move-after = False
filter = 
force-filter = False
```

Keeping original and transcoded audio just makes the file bigger...

**Comment by mdhiggins** [comment] 2020-12-09 18:55
The tagging now coming after the conversion is a direct consequence of the feature you requested. Because determining the tag language is done based on the default audio track of the newly created file, tagging cannot be performed until after that data is available.

Guessit is the module that does the filename guessing and it looks like its just getting confused based on the complicated filenames and alternate languages. I'm not sure how great its non-english support is but I don't write that module. You can try messing around with the `full-pass-guess` option to see if  that increases accuracy when turned off. For the specific error you posted it looks like guessit thought it was a TV show when its a movie and that's partly why it failed. Using a media manager like Radarr or Sonarr will be helpful here as they pass the ID directly to the script so there's no guessing involved.

With regards to your final question. It sounds like you should just not use the universal audio option. That option is designed to create an extra duplicate audio track for maximum compatibility. Just turn that off by setting the codec to blank `codec = ` and set your general audio options to whatever you want.

**Closed by mdhiggins** 2020-12-09 18:55 UTC
