### ISSUE TITLE
AAC 2ch conversion results in 0 bitrate.

### ISSUE THREAD

**Issue by morganzero** [mdhiggins/sickbeard_mp4_automator#1111] opened 2020-01-03 14:45 UTC
Hi,

I discovered the issue when I decided to configure ``audio-channel-bitrate = 0`` to mirror the original audio source as described in the readme file. If I put in ``256``or just leave it blank it will do as expected of it. But only when I put in ``0`` it "fails". I'm sure I'm causing this without knowing how. I'm kinda hoping for some shed of light on this issue.

**This is how the conversion looks like:**

```
:~/automator_manual$ ./manual.py
Manual processor started.
/path/bin/python
64bit Python.
Enter path to file:
#: /path/
Processing file /path/film.mkv
Reading video stream.
Video codec detected: h264.
Pix Fmt: yuv420p.
Profile: High.
Reading audio streams.
No audio streams detected in any appropriate language, relaxing restrictions so there will be some audio stream present.
Audio detected for stream #1: aac [eng].
Creating audio stream 0 from source audio stream 1 [iOS-audio].
Creating audio stream 1 from source stream 1.
Unable to determine audio bitrate from source stream 1, defaulting to 256 per channel.
Audio language array is empty.
Reading subtitle streams.
Attempting to download subtitles.
Subtitle stream array is empty.
{
    "preopts": [], 
    "subtitle": {}, 
    "format": "mp4", 
    "postopts": [
        "-threads", 
        "2"
    ], 
    "video": {
        "profile": null, 
        "map": 0, 
        "level": null, 
        "codec": "copy", 
        "bitrate": 2635.567, 
        "pix_fmt": null
    }, 
    "audio": {
        "0": {
            "map": 1, 
            "language": "eng", 
            "channels": 2, 
            "codec": "aac", 
            "disposition": "none", 
            "bitrate": 0, 
            "filter": null
        }, 
        "1": {
            "map": 1, 
            "language": "eng", 
            "channels": 6, 
            "codec": "copy", 
            "disposition": "none", 
            "bitrate": 1536, 
            "filter": null
        }
    }
}
Starting conversion.
[          ] 7%
```

**This is the result:**

```
Audio #1
ID :
2
Format :
AAC LC
Format/Info :
Advanced Audio Codec Low Complexity
Codec ID :
mp4a-40-2
Duration :
3 h 10 min
Duration_LastFrame :
-11 ms
Bit rate mode :
Constant
Bit rate :
21.8 kb/s
Channel(s) :
2 channels
Channel layout :
L R
Sampling rate :
48.0 kHz
Frame rate :
46.875 FPS (1024 SPF)
Compression mode :
Lossy
Stream size :
29.7 MiB (0%)
Language :
English
Default :
Yes
Alternate group :
1
Menus :
5
```

**And this is my configuration:**

```
[MP4]
ffmpeg = /home29/morganzero/bin/ffmpeg
ffprobe = /home29/morganzero/bin/ffprobe
threads = 2
output_directory =
copy_to =
move_to =
output_extension = mp4
output_format = mp4
delete_original = True
relocate_moov = False
video-codec = h264,x264,h.264,x.264,X264,H264
video-bitrate =
video-crf =
video-max-width =
video-profile =
h264-max-level =
use-qsv-decoder-with-encoder = True
use-hevc-qsv-decoder = False
enable_dxva2_gpu_decode = False
ios-audio = True
ios-first-track-only = False
ios-audio-filter =
ios-move-last = False
max-audio-channels =
audio-codec = aac
ignore-truehd = True
audio-language =
audio-default-language =
audio-channel-bitrate = 0
audio-filter =
audio-copy-original = True
audio-first-track-of-language = False
subtitle-codec = srt
subtitle-language = eng,swe,sve
subtitle-default-language =
subtitle-encoding =
bad-internal-subtitle-sources = pgssub, hdmv_pgs_subtitle, s_hdmv/pgs, dvdsub, dvd_subtitle, dvb_teletext, dvb_subtitle
bad-external-subtitle-sources = dvdsub, dvd_subtitle, dvb_teletext, dvb_subtitle
fullpathguess = True
convert-mp4 = False
force-convert = False
tagfile = True
tag-language = en
download-artwork = Poster
download-subs = True
embed-subs = False
embed-only-internal-subs = False
sub-providers = addic7ed,podnapisi,thesubdb,opensubtitles
permissions = 0777
post-process = False
pix-fmt =
aac_adtstoasc = False
```

When streaming the 2ch audio it sounds really funny. Kinda distorted.

Hopefully, this is an easy fix on my side. I appreciate any help. Thanks!

**Comment by morganzero** [comment] 2020-01-26 12:07
Can I share any other info to make this work?

**Comment by mdhiggins** [comment] 2020-01-26 14:50
Don’t set your audio channel bitrate  to 0 just leave it blank

**Comment by morganzero** [comment] 2020-01-26 14:58
Yes that's what I am doing at the moment. But I'm reporting an issue referring to the readme file where it says that `0` will mirror the original audio source. Leaving it blank will only set the bitrate to `256` as default.

**Comment by mdhiggins** [comment] 2020-01-26 15:29
I think I see what the problem is, you are correct leaving blank isn't the right way to go but it looks like there was a problem where for iOS audio track the guess of the bitrate wouldn't take place and it would leave it as zero
Previously I used to have a filter that would block 0 from making it to FFMPEG but I had removed that and now this error is being caught and revealing the feature probably never quite worked correctly

I just pushed an update that should fix this for iOS audio
I also updated the guessed bitrate equation to this
` ( audio stream bitrate / channels ) * output channnels ` which should preserve the per channel bitrate across conversions

**Comment by morganzero** [comment] 2020-01-26 15:38
Just so I understand 100%. If I want to mirror the original audio source, should I put `0`or leave it blank? :)

And thanks!

**Comment by mdhiggins** [comment] 2020-01-26 16:57
Put it at 0

**Comment by mdhiggins** [comment] 2020-01-26 17:01
I just pushed another update that will have blank and 0 behave the same so there's no more confusion there as well
62cc5f4e27a82785e31bef8e86d55728473f9ef3
3aa7f37f88cc429d97d7f01d694d609e328f232e

**Comment by morganzero** [comment] 2020-01-26 18:15
Thanks alot! :)

**Comment by morganzero** [comment] 2020-01-26 18:23
Awesome! Is it OK to only replace `mkvtomp4.py` and `readSettings.py`with the new ones'?

Thanks again!

**Comment by mdhiggins** [comment] 2020-01-26 18:27
Yeah those are the only two files changed

**Comment by mdhiggins** [comment] 2020-01-26 20:46
Feel free to close this issue if that fixed things

**Closed** 2020-01-26 20:50 UTC
