### ISSUE TITLE
Sonarr/Radarr Auto Rename

### ISSUE THREAD

**Issue by Protektor-Desura** [mdhiggins/sickbeard_mp4_automator#1530] opened 2022-02-08 03:59 UTC
I have been getting errors in Sonarr and Radarr for the renaming function in SMA for about a month or so now. It processes the file correct and even processes everything perfectly but when it triggers the rename part it fails and doesn't trigger Radarr or Sonarr to actually rename the files. It thinks they are proper but if you tell both of them to rescan the directories it sees the filename with the rnm in the filename at the end and then you can manually trigger a rename.

I have checked the apikey in the ini 3 times for Radarr and Sonarr and it is correct. So I am not sure of the issue.

**Comment by mdhiggins** [comment] 2022-02-08 04:51
Post some logs

**Comment by Protektor-Desura** [comment] 2022-02-08 06:03
2022-02-07 16:21:15.5|Error|CommandExecutor|Error occurred while executing task RenameFiles

[v3.0.6.1457] NzbDrone.Core.Datastore.ModelNotFoundException: Series with ID 0 does not exist
  at NzbDrone.Core.Datastore.BasicRepository`1[TModel].Get (System.Int32 id) [0x00021] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Datastore\BasicRepository.cs:85 
  at NzbDrone.Core.Tv.SeriesService.GetSeries (System.Int32 seriesId) [0x00000] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Tv\SeriesService.cs:58 
  at NzbDrone.Core.MediaFiles.RenameEpisodeFileService.Execute (NzbDrone.Core.MediaFiles.Commands.RenameFilesCommand message) [0x00000] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\MediaFiles\RenameEpisodeFileService.cs:159 
  at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand] (TCommand command, NzbDrone.Core.Messaging.Commands.CommandModel commandModel) [0x000e0] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:96 
  at (wrapper dynamic-method) System.Object.CallSite.Target(System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,NzbDrone.Core.Messaging.Commands.CommandExecutor,object,NzbDrone.Core.Messaging.Commands.CommandModel)
  at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2] (System.Runtime.CompilerServices.CallSite site, T0 arg0, T1 arg1, T2 arg2) [0x0008b] in <5b415632df1f4365ae2242b1a257bb5b>:0 
  at (wrapper dynamic-method) System.Object.CallSite.Target(System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,NzbDrone.Core.Messaging.Commands.CommandExecutor,object,NzbDrone.Core.Messaging.Commands.CommandModel)
  at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands () [0x00027] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:41 

2022-02-07 16:21:15.5|Error|CommandExecutor|Error occurred while executing task RenameFiles

[v3.0.6.1457] NzbDrone.Core.Datastore.ModelNotFoundException: Series with ID 0 does not exist
  at NzbDrone.Core.Datastore.BasicRepository`1[TModel].Get (System.Int32 id) [0x00021] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Datastore\BasicRepository.cs:85 
  at NzbDrone.Core.Tv.SeriesService.GetSeries (System.Int32 seriesId) [0x00000] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Tv\SeriesService.cs:58 
  at NzbDrone.Core.MediaFiles.RenameEpisodeFileService.Execute (NzbDrone.Core.MediaFiles.Commands.RenameFilesCommand message) [0x00000] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\MediaFiles\RenameEpisodeFileService.cs:159 
  at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand] (TCommand command, NzbDrone.Core.Messaging.Commands.CommandModel commandModel) [0x000e0] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:96 
  at (wrapper dynamic-method) System.Object.CallSite.Target(System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,NzbDrone.Core.Messaging.Commands.CommandExecutor,object,NzbDrone.Core.Messaging.Commands.CommandModel)
  at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands () [0x00027] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:41 

2022-02-07 16:21:15.5|Error|CommandExecutor|Error occurred while executing task RenameFiles

[v3.0.6.1457] NzbDrone.Core.Datastore.ModelNotFoundException: Series with ID 0 does not exist
  at NzbDrone.Core.Datastore.BasicRepository`1[TModel].Get (System.Int32 id) [0x00021] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Datastore\BasicRepository.cs:85 
  at NzbDrone.Core.Tv.SeriesService.GetSeries (System.Int32 seriesId) [0x00000] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Tv\SeriesService.cs:58 
  at NzbDrone.Core.MediaFiles.RenameEpisodeFileService.Execute (NzbDrone.Core.MediaFiles.Commands.RenameFilesCommand message) [0x00000] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\MediaFiles\RenameEpisodeFileService.cs:159 
  at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand] (TCommand command, NzbDrone.Core.Messaging.Commands.CommandModel commandModel) [0x000e0] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:96 
  at (wrapper dynamic-method) System.Object.CallSite.Target(System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,NzbDrone.Core.Messaging.Commands.CommandExecutor,object,NzbDrone.Core.Messaging.Commands.CommandModel)
  at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands () [0x00027] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:41 

2022-02-07 16:21:15.5|Error|CommandExecutor|Error occurred while executing task RenameFiles

[v3.0.6.1457] NzbDrone.Core.Datastore.ModelNotFoundException: Series with ID 0 does not exist
  at NzbDrone.Core.Datastore.BasicRepository`1[TModel].Get (System.Int32 id) [0x00021] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Datastore\BasicRepository.cs:85 
  at NzbDrone.Core.Tv.SeriesService.GetSeries (System.Int32 seriesId) [0x00000] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Tv\SeriesService.cs:58 
  at NzbDrone.Core.MediaFiles.RenameEpisodeFileService.Execute (NzbDrone.Core.MediaFiles.Commands.RenameFilesCommand message) [0x00000] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\MediaFiles\RenameEpisodeFileService.cs:159 
  at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand] (TCommand command, NzbDrone.Core.Messaging.Commands.CommandModel commandModel) [0x000e0] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:96 
  at (wrapper dynamic-method) System.Object.CallSite.Target(System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,NzbDrone.Core.Messaging.Commands.CommandExecutor,object,NzbDrone.Core.Messaging.Commands.CommandModel)
  at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands () [0x00027] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:41 

2022-02-07 16:21:15.5|Error|CommandExecutor|Error occurred while executing task RenameFiles

[v3.0.6.1457] NzbDrone.Core.Datastore.ModelNotFoundException: Series with ID 0 does not exist
  at NzbDrone.Core.Datastore.BasicRepository`1[TModel].Get (System.Int32 id) [0x00021] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Datastore\BasicRepository.cs:85 
  at NzbDrone.Core.Tv.SeriesService.GetSeries (System.Int32 seriesId) [0x00000] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Tv\SeriesService.cs:58 
  at NzbDrone.Core.MediaFiles.RenameEpisodeFileService.Execute (NzbDrone.Core.MediaFiles.Commands.RenameFilesCommand message) [0x00000] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\MediaFiles\RenameEpisodeFileService.cs:159 
  at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand] (TCommand command, NzbDrone.Core.Messaging.Commands.CommandModel commandModel) [0x000e0] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:96 
  at (wrapper dynamic-method) System.Object.CallSite.Target(System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,NzbDrone.Core.Messaging.Commands.CommandExecutor,object,NzbDrone.Core.Messaging.Commands.CommandModel)
  at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands () [0x00027] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:41 

2022-02-07 16:21:15.5|Error|CommandExecutor|Error occurred while executing task RenameFiles

[v3.0.6.1457] NzbDrone.Core.Datastore.ModelNotFoundException: Series with ID 0 does not exist
  at NzbDrone.Core.Datastore.BasicRepository`1[TModel].Get (System.Int32 id) [0x00021] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Datastore\BasicRepository.cs:85 
  at NzbDrone.Core.Tv.SeriesService.GetSeries (System.Int32 seriesId) [0x00000] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Tv\SeriesService.cs:58 
  at NzbDrone.Core.MediaFiles.RenameEpisodeFileService.Execute (NzbDrone.Core.MediaFiles.Commands.RenameFilesCommand message) [0x00000] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\MediaFiles\RenameEpisodeFileService.cs:159 
  at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand] (TCommand command, NzbDrone.Core.Messaging.Commands.CommandModel commandModel) [0x000e0] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:96 
  at (wrapper dynamic-method) System.Object.CallSite.Target(System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,NzbDrone.Core.Messaging.Commands.CommandExecutor,object,NzbDrone.Core.Messaging.Commands.CommandModel)
  at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands () [0x00027] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:41 

2022-02-07 16:21:15.5|Error|CommandExecutor|Error occurred while executing task RenameFiles

[v3.0.6.1457] NzbDrone.Core.Datastore.ModelNotFoundException: Series with ID 0 does not exist
  at NzbDrone.Core.Datastore.BasicRepository`1[TModel].Get (System.Int32 id) [0x00021] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Datastore\BasicRepository.cs:85 
  at NzbDrone.Core.Tv.SeriesService.GetSeries (System.Int32 seriesId) [0x00000] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Tv\SeriesService.cs:58 
  at NzbDrone.Core.MediaFiles.RenameEpisodeFileService.Execute (NzbDrone.Core.MediaFiles.Commands.RenameFilesCommand message) [0x00000] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\MediaFiles\RenameEpisodeFileService.cs:159 
  at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand] (TCommand command, NzbDrone.Core.Messaging.Commands.CommandModel commandModel) [0x000e0] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:96 
  at (wrapper dynamic-method) System.Object.CallSite.Target(System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,NzbDrone.Core.Messaging.Commands.CommandExecutor,object,NzbDrone.Core.Messaging.Commands.CommandModel)
  at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands () [0x00027] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:41 

2022-02-07 16:21:15.5|Error|CommandExecutor|Error occurred while executing task RenameFiles

[v3.0.6.1457] NzbDrone.Core.Datastore.ModelNotFoundException: Series with ID 0 does not exist
  at NzbDrone.Core.Datastore.BasicRepository`1[TModel].Get (System.Int32 id) [0x00021] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Datastore\BasicRepository.cs:85 
  at NzbDrone.Core.Tv.SeriesService.GetSeries (System.Int32 seriesId) [0x00000] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Tv\SeriesService.cs:58 
  at NzbDrone.Core.MediaFiles.RenameEpisodeFileService.Execute (NzbDrone.Core.MediaFiles.Commands.RenameFilesCommand message) [0x00000] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\MediaFiles\RenameEpisodeFileService.cs:159 
  at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand] (TCommand command, NzbDrone.Core.Messaging.Commands.CommandModel commandModel) [0x000e0] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:96 
  at (wrapper dynamic-method) System.Object.CallSite.Target(System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,NzbDrone.Core.Messaging.Commands.CommandExecutor,object,NzbDrone.Core.Messaging.Commands.CommandModel)
  at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands () [0x00027] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:41 

2022-02-07 16:21:15.5|Error|CommandExecutor|Error occurred while executing task RenameFiles

[v3.0.6.1457] NzbDrone.Core.Datastore.ModelNotFoundException: Series with ID 0 does not exist
  at NzbDrone.Core.Datastore.BasicRepository`1[TModel].Get (System.Int32 id) [0x00021] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Datastore\BasicRepository.cs:85 
  at NzbDrone.Core.Tv.SeriesService.GetSeries (System.Int32 seriesId) [0x00000] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Tv\SeriesService.cs:58 
  at NzbDrone.Core.MediaFiles.RenameEpisodeFileService.Execute (NzbDrone.Core.MediaFiles.Commands.RenameFilesCommand message) [0x00000] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\MediaFiles\RenameEpisodeFileService.cs:159 
  at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand] (TCommand command, NzbDrone.Core.Messaging.Commands.CommandModel commandModel) [0x000e0] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:96 
  at (wrapper dynamic-method) System.Object.CallSite.Target(System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,NzbDrone.Core.Messaging.Commands.CommandExecutor,object,NzbDrone.Core.Messaging.Commands.CommandModel)
  at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands () [0x00027] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:41 

2022-02-07 16:21:15.5|Error|CommandExecutor|Error occurred while executing task RenameFiles

[v3.0.6.1457] NzbDrone.Core.Datastore.ModelNotFoundException: Series with ID 0 does not exist
  at NzbDrone.Core.Datastore.BasicRepository`1[TModel].Get (System.Int32 id) [0x00021] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Datastore\BasicRepository.cs:85 
  at NzbDrone.Core.Tv.SeriesService.GetSeries (System.Int32 seriesId) [0x00000] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Tv\SeriesService.cs:58 
  at NzbDrone.Core.MediaFiles.RenameEpisodeFileService.Execute (NzbDrone.Core.MediaFiles.Commands.RenameFilesCommand message) [0x00000] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\MediaFiles\RenameEpisodeFileService.cs:159 
  at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand] (TCommand command, NzbDrone.Core.Messaging.Commands.CommandModel commandModel) [0x000e0] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:96 
  at (wrapper dynamic-method) System.Object.CallSite.Target(System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,NzbDrone.Core.Messaging.Commands.CommandExecutor,object,NzbDrone.Core.Messaging.Commands.CommandModel)
  at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands () [0x00027] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:41 

2022-02-07 16:21:15.5|Error|CommandExecutor|Error occurred while executing task RenameFiles

[v3.0.6.1457] NzbDrone.Core.Datastore.ModelNotFoundException: Series with ID 0 does not exist
  at NzbDrone.Core.Datastore.BasicRepository`1[TModel].Get (System.Int32 id) [0x00021] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Datastore\BasicRepository.cs:85 
  at NzbDrone.Core.Tv.SeriesService.GetSeries (System.Int32 seriesId) [0x00000] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Tv\SeriesService.cs:58 
  at NzbDrone.Core.MediaFiles.RenameEpisodeFileService.Execute (NzbDrone.Core.MediaFiles.Commands.RenameFilesCommand message) [0x00000] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\MediaFiles\RenameEpisodeFileService.cs:159 
  at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand] (TCommand command, NzbDrone.Core.Messaging.Commands.CommandModel commandModel) [0x000e0] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:96 
  at (wrapper dynamic-method) System.Object.CallSite.Target(System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,NzbDrone.Core.Messaging.Commands.CommandExecutor,object,NzbDrone.Core.Messaging.Commands.CommandModel)
  at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands () [0x00027] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:41 

2022-02-07 16:21:15.5|Error|CommandExecutor|Error occurred while executing task RenameFiles

[v3.0.6.1457] NzbDrone.Core.Datastore.ModelNotFoundException: Series with ID 0 does not exist
  at NzbDrone.Core.Datastore.BasicRepository`1[TModel].Get (System.Int32 id) [0x00021] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Datastore\BasicRepository.cs:85 
  at NzbDrone.Core.Tv.SeriesService.GetSeries (System.Int32 seriesId) [0x00000] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Tv\SeriesService.cs:58 
  at NzbDrone.Core.MediaFiles.RenameEpisodeFileService.Execute (NzbDrone.Core.MediaFiles.Commands.RenameFilesCommand message) [0x00000] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\MediaFiles\RenameEpisodeFileService.cs:159 
  at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand] (TCommand command, NzbDrone.Core.Messaging.Commands.CommandModel commandModel) [0x000e0] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:96 
  at (wrapper dynamic-method) System.Object.CallSite.Target(System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,NzbDrone.Core.Messaging.Commands.CommandExecutor,object,NzbDrone.Core.Messaging.Commands.CommandModel)
  at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands () [0x00027] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Messaging\Comm

**Comment by mdhiggins** [comment] 2022-02-08 06:27
I can look at these but I mostly need the sma logs

The logs are in the script config folder with autoProcess.ini named sma.log

**Comment by mdhiggins** [comment] 2022-02-08 06:47
I am seeing quite a few of the following errors

2022-02-07 16:21:15.5|Error|CommandExecutor|Error occurred while executing task RenameFiles

[v3.0.6.1457] NzbDrone.Core.Datastore.ModelNotFoundException: Series with ID 0 does not exist

Looks like it's trying to use ID 0 which isn't correct. The SMA logs especially the debug logs (see the wiki) will be very helpful here to see if the wrong ID is being send or if this a problem on Sonarrs end


Also are you definitely seeing the same issue on Radarr as well? They use different approaches for the rename API call so I'm curious if both are exhibiting the issue

**Comment by mdhiggins** [comment] 2022-02-08 19:49
Are you seeing a similar error in the Radarr logs equivalent to the Sonarr `Error occurred while executing task RenameFiles` error?

**Comment by Protektor-Desura** [comment] 2022-02-08 19:52
Yes

**Comment by mdhiggins** [comment] 2022-02-08 19:56
Could you post an example of that error as well

**Comment by Protektor-Desura** [comment] 2022-02-08 20:02
I'm not finding an error specifically saying there was an error on renaming in the logs but I have 40+ movies with rnm still in the filename.

AVP Alien vs. Predator (2004) [Bluray-1080p AV1 8bit Opus 2.0].rnm.mkv
Finding Nemo (2003) [Bluray-1080p AV1 8bit Opus 2.0[EN+FR+ES+JA]].rnm.mkv
Robin Hood (1973) [Bluray-1080p x265 10bit AAC 5.1].rnm.mkv
Toy Story 2 (1999) [Bluray-1080p AV1 8bit Opus 2.0].rnm.mkv

**Comment by Protektor-Desura** [comment] 2022-02-08 20:08
2022-02-08 05:57:53.0|Info|RecycleBinProvider|Recycling Bin has not been configured, deleting permanently. /libraries/movies/AVP Alien vs. Predator (2004)/AVP Alien vs. Predator (2004) [Bluray-1080p AV1 8bit Opus 2.0].mkv
2022-02-08 05:57:53.4|Info|RecycleBinProvider|Recycling Bin has not been configured, deleting permanently. /libraries/movies/AVP Alien vs. Predator (2004)/AVP Alien vs. Predator (2004) [Bluray-1080p AV1 8bit Opus 2.0].en.srt
2022-02-08 05:58:15.3|Info|MovieService|Assigning file [AVP Alien vs. Predator (2004) [Bluray-1080p AV1 8bit Opus 2.0].mkv] to movie [[AVP: Alien vs. Predator (2004)][tt0370263, 395]]
2022-02-08 05:58:37.4|Info|DiskScanService|Scanning disk for AVP: Alien vs. Predator
2022-02-08 05:58:37.4|Info|MovieService|Assigning file [AVP Alien vs. Predator (2004) [Bluray-1080p AV1 8bit Opus 2.0].rnm.mkv] to movie [[AVP: Alien vs. Predator (2004)][tt0370263, 395]]
2022-02-08 05:58:37.4|Info|DiskScanService|Completed scanning disk for AVP: Alien vs. Predator

**Comment by mdhiggins** [comment] 2022-02-08 20:34
The command on Radarr differs slightly and would be called "RenameMovie" if that's helpful

**Comment by mdhiggins** [comment] 2022-02-08 22:19
376274f614301068e165eab8b183937552852af4

This includes adjustments for the radarr and sonarr renaming issue

I am unable to reproduce the Radarr renaming issue specifically but Sonarr was having issues related to an undocumented change in the Sonarr API. The Sonarr API now requires the seriesId to be included in the `RenameFiles` command parameters which is not included on their documentation but was evident after reviewing the source code. This is now included

I also migrated the Radarr rename command from `RenameMovie` to `RenameFiles` to be more consistent with the Sonarr equivalent and while I was unable to reproduce your issue on Radarr the rename worked after this change on my testing so hopefully this adjustment will resolve that issue as well

**Comment by Protektor-Desura** [comment] 2022-02-08 22:20
Sorry not finding an error in the logs but I do have 40+ movies with rnm in the title like I posted above.

**Comment by mdhiggins** [comment] 2022-02-08 22:25
Should hopefully be resolved with the above update, please test and close if fixed or report back with additional information if the issue persists

**Comment by Protektor-Desura** [comment] 2022-02-10 06:36
Fixed it. Thanks

**Closed** 2022-02-10 06:37 UTC
Labels: bug
