### ISSUE TITLE
Manual.py and subtitles (for iOS devices)

### ISSUE THREAD

**Issue by dpkmon** [mdhiggins/sickbeard_mp4_automator#423] opened 2016-02-07 02:15 UTC
Hi everyone, hope you are all doing well.

I'm having the following issue.

I'm running the automator manually to convert from mkv to mp4 plus subtitles.

The convertion goes flawlesly, however on my iOS device (Iphone 6s Plus) subs aren't showing. (they are being downloaded)

Here's the log. Any tips are greatly appreciated. (manual.py -i C:\VIDEO\COMPLETED -a)

> 2016-02-06 23:03:57 - MANUAL - INFO - Manual processor started.
2016-02-06 23:03:57 - MANUAL - WARNING - Audio bitrate was invalid, defaulting to 256 per channel.
2016-02-06 23:03:57 - MANUAL - WARNING - Video bitrate must be greater than 0, defaulting to no video bitrate cap.
2016-02-06 23:04:15 - MANUAL - INFO - Reading video stream.
2016-02-06 23:04:15 - MANUAL - INFO - Video codec detected: h264.
2016-02-06 23:04:15 - MANUAL - INFO - Pix Fmt: yuv420p.
2016-02-06 23:04:15 - MANUAL - INFO - Reading audio streams.
2016-02-06 23:04:15 - MANUAL - INFO - Audio detected for stream #1: ac3 [und].
2016-02-06 23:04:15 - MANUAL - INFO - Creating audio stream 0 from source audio stream 1 [iOS-audio].
2016-02-06 23:04:15 - MANUAL - INFO - Creating audio stream 1 from source stream 1.
2016-02-06 23:04:15 - MANUAL - INFO - Reading subtitle streams.
2016-02-06 23:04:15 - MANUAL - INFO - Attempting to download subtitles.
2016-02-06 23:04:53 - MANUAL - INFO - External eng subtitle file detected.
2016-02-06 23:04:53 - MANUAL - INFO - Creating subtitle stream 0 by importing Family.Guy.S14E12.720p.HDTV.x264-KILLERS.en.srt.
2016-02-06 23:04:53 - MANUAL - INFO - {
    "subtitle": {
        "0": {
            "path": "C:\\VIDEO\\COMPLETED\\Family.Guy.S14E12.720p.HDTV.x264-KILLERS[rarbg]\\Family.Guy.S14E12.720p.HDTV.x264-KILLERS.en.srt", 
            "map": 0, 
            "codec": "mov_text", 
            "language": "eng", 
            "source": 1
        }
    }, 
    "audio": {
        "0": {
            "channels": 2, 
            "map": 1, 
            "codec": "aac", 
            "bitrate": 256, 
            "language": "eng"
        }, 
        "1": {
            "channels": 2, 
            "map": 1, 
            "codec": "ac3", 
            "bitrate": 512, 
            "language": "eng"
        }
    }, 
    "video": {
        "map": 0, 
        "codec": "copy", 
        "bitrate": 1451.5638999999999, 
        "level": null
    }, 
    "format": "mov"
}
2016-02-06 23:04:53 - MANUAL - INFO - Starting conversion.
2016-02-06 23:05:55 - MANUAL - INFO - C:\VIDEO\CONVERTIDO\Family.Guy.S14E12.720p.HDTV.x264-KILLERS.mp4 created.
2016-02-06 23:05:56 - MANUAL - INFO - Tagging file: C:\VIDEO\CONVERTIDO\Family.Guy.S14E12.720p.HDTV.x264-KILLERS.mp4.
2016-02-06 23:05:57 - MANUAL - INFO - Trying to write tags.
2016-02-06 23:05:57 - MANUAL - INFO - Tags written successfully.
>

**Comment by mdhiggins** [comment] 2016-02-07 03:48
What app are you using to play your media on iOS?

**Comment by dpkmon** [comment] 2016-02-07 10:59
Default video !
Nicolás Torchio.
11-2632-5402

    _____________________________

**Comment by mdhiggins** [comment] 2016-02-07 14:37
Did you press the little subtitle icon and select the subtitle track you wish to display within the default player?

The little icon that looks like a chat bubble

**Comment by dpkmon** [comment] 2016-02-07 14:40
The icon's not there.
If I play the file On my pc with VLC, the subs are there (just very small)






On Sun, Feb 7, 2016 at 6:37 AM -0800, "Michael Higgins" <notifications@github.com> wrote:










Did you press the little subtitle icon and select the subtitle track you wish to display within the default player?



The little icon that looks like a chat bubble

**Comment by dpkmon** [comment] 2016-02-10 01:06
Same happens if i Run uTorrent Post download.

**Comment by mdhiggins** [comment] 2016-02-12 17:08
Definitely looks like everything is working as it should on the conversion side, suspect this is a bug with iOS or an issue where iTunes is converting the file before its transferred to the device and you're losing your subs as a result

**Comment by dpkmon** [comment] 2016-02-12 17:24
Ok, if you can think of any workaround or solution, let me know if I can
help.

Thanks!

**Comment by dpkmon** [comment] 2016-02-13 22:23
Small update, when playing the file with itunes, subs are also missing.

**Comment by conradhagemans** [comment] 2016-02-18 21:01
Do you work on an Apple Mac? Then download Subler and open the converted file with it. Does it show subtitles? You can download subler here: https://bitbucket.org/galad87/subler/wiki/Home
Also a great tool to add a subtitle or download all movie info/ cover etc.

What is the extension of the vonverted file? .mp4 or .m4v
Otherwise change it in the .ini file:
output_extension = m4v

**Comment by dpkmon** [comment] 2016-02-18 21:03
Nop, Windows 10!
I'll try the m4v format.

Nicolás Torchio.
11-2632-5402




On Thu, Feb 18, 2016 at 1:01 PM -0800, "Conrad Hagemans" <notifications@github.com> wrote:












Do you work on an Apple Mac? Then download Subler and open the converted file with it. Does it show subtitles? You can download subler here: https://bitbucket.org/galad87/subler/wiki/Home

Also a great tool to add a subtitle or download all movie info/ cover etc.



What is the extension of the vonverted file? .mp4 or .m4v

Otherwise change it in the .ini file:

output_extension = m4v

**Comment by mdhiggins** [comment] 2016-03-18 04:43
I can't seem to reproduce this problem at all, anyone else on iOS/OSX having issues with subtitles?

**Closed** 2016-03-18 17:53 UTC
