### ISSUE TITLE
Feature Request: Keep unique-streams-of-language (audio and subtitles)

### ISSUE THREAD

**Issue by RandomNinjaAtk** [mdhiggins/sickbeard_mp4_automator#1293] opened 2020-08-03 13:02 UTC
Currently SMA has the ability to keep multiple streams of the same language for audio/subtitle or the first stream of each (first-stream-of-language). This request would be a middle ground between first stream and all streams... This feature would keep only streams that have unique flags in the desired language. Example would be:

Incoming file has 3 audio streams, and 3 subtitle streams.

Audio:
1st is 5.1 surround sound
2nd is 2.0
3rd is commentary

Subtitle
1st is Forced
2nd is Regular
3rd is Regular

The resulting output file would be:

Audio
1st is 5.1
2nd is Commentary

Subtitle
1st is forced, and marked as forced
2nd is regular

So the resulting file would remove duplicates that are not unique by flag to provide some reduction in size.

Also one possible issue with the current implementation for subtitles when using: first-stream-of-language... That setting might be problematic when you have a file with forced and regular subtitles, it would likely only keep the forced subs because it would qualify as the first stream, when in reality you'd want to keep both in that situation.

**Comment by mdhiggins** [comment] 2020-08-03 15:41
This would be particularly challenging to implement due to a high number of possible scenarios and would also be very error prone as the disposition flags are quite inconsistently set in most source files.

I think a better solution rather than trying to tie all this together with the first of language option would be to maybe have something like an 'ignored disposition' option where you could opt not to include things like commentary as an alternative to the first language option though that still wouldn't produce what you wanted above

This seems like a relatively large undertaking that would produce probably inconsistent results and only apply to edge case scenarios (how often are you really encountering source material with multiple types of specifically flagged disposition tracks under the same language? It would be <1% of my multi terabyte library). Subtitles would maybe be the most common scenario where you have forced and default I guess but if that's your issue and the goal is space saving its a large development undertaking for <100kb of space saved per subtitle track avoided.

I'm open to further discussion and would encourage a pull request which I'm happy to review but this would be challenging to implement

**Comment by RandomNinjaAtk** [comment] 2020-08-03 15:54
I guess in a way its not about saving space as much as possibly clearing up confusion. Because of the need to keep all streams enabled for Subtitles, I often see results like this:

![image](https://user-images.githubusercontent.com/8386416/89201693-e2272300-d57f-11ea-894f-4a2f3d1035b2.png)

This case, 4 streams, 3 of them look identical. I feel like that would be confusing to look at for most users. But I can't use the reduce to single stream for subtitles or you will drop full subs, when you want to have both.

Maybe an alternative would be for Subtitles only, when keeping single stream only. If forced exists, keep the forced plus the first non forced stream...

**Comment by mdhiggins** [comment] 2020-08-03 17:11
https://github.com/mdhiggins/sickbeard_mp4_automator/tree/unique-dispositions

See if that helps

Added two new options to audio and subtitle sections
```
ignored-dispositions = 
unique-dispositions = False
```

Ignored is easy, will ignore source material containing those dispositions
Unique will only include one unique set of dispositions per track per language

Might have unanticipated consequences but tried to apply it universally across audio, sub, external, extracted, and embedded subs. Burn subtitles are not impacted as these are handled uniquely

**Comment by mdhiggins** [comment] 2020-08-03 17:12
If you can test it for stability and desired effect and it works for you I'll merge it back to master
It's passing my initial tests and seems to be working as intended

This bulk of the work is done by this function
```
    def validDisposition(self, language, disposition, ignored=[], unique=False, existing=[], append=True):
        dispodict = self.dispoStringToDict(disposition)
        truedispositions = [x for x in dispodict if dispodict[x]]
        for dispo in truedispositions:
            if dispo in ignored:
                self.log.debug("Ignoring stream because disposition %s is on the ignore list." % (dispo))
                return False
        if unique:
            search = "%s.%s" % (language, disposition)
            if search in existing:
                self.log.debug("Invalid disposition, stream fitting this disposition profile already exists, ignoring.")
                return False
            if append:
                self.log.debug("Valid disposition, adding %s to the ignored list." % (search))
                existing.append(search)
            return True
        return True
```

which is applied essentially after any valid language check

**Comment by RandomNinjaAtk** [comment] 2020-08-03 17:47
Thanks I'll give it a try and report back!

**Comment by RandomNinjaAtk** [comment] 2020-08-03 18:05
So for right now the few quick tests that I've done it seems to work, my current settings are this for subs:

```
[Subtitle]
codec = srt
codec-image-based = pgs
languages = eng
default-language = eng
first-stream-of-language = False
encoding = 
burn-subtitles = False
burn-dispositions = forced
download-subs = False
download-hearing-impaired-subs = False
download-providers = 
embed-subs = True
embed-image-subs = True
embed-only-internal-subs = True
filename-dispositions = forced
ignore-embedded-subs = False
attachment-codec = 
ignored-dispositions =
unique-dispositions = True
```

And the result is doing what I expected, on a file with 2 subs that are not unique, it was reduced to one subtitle track. I'm still testing it though as much as possible. But it looks to be working!

**Comment by RandomNinjaAtk** [comment] 2020-08-03 20:42
So quick update, seems to be working as expected. Others may also want to test though...

Thanks!

**Comment by mdhiggins** [comment] 2020-08-05 15:06
Merged with master branch for now, will close but feel free to reopen if any issues are encountered

**Closed by mdhiggins** 2020-08-05 15:06 UTC
Labels: enhancement
