### ISSUE TITLE
Help! Script performance in gimp mode

### ISSUE THREAD

**Issue by justinglock40** [mdhiggins/sickbeard_mp4_automator#718] opened 2017-04-13 22:46 UTC
So my issue is that the script is working as designed. However, on my Dual E5-2660 Xeon (16 core, 32 threads, approx. 17,000 passmark) is not breaking 5% utilization and I can not for the life of me figure out why it's gimped.

![capture](https://cloud.githubusercontent.com/assets/23133649/25027264/ec83c154-2070-11e7-8e09-51ac4664eba6.PNG)

Also here are my autoProcess settings if this can help at all:

[MP4]
ffmpeg = C:\ffmpeg\bin\ffmpeg.exe
ffprobe = C:\ffmpeg\bin\ffprobe.exe
threads = auto
output_directory = 
copy_to = 
move_to = 
output_extension = mp4
output_format = mp4
delete_original = True
relocate_moov = True
video-codec = h264,x264,hevc,h265,x265,HEVC,mpeg4,MPEG-4,MPEG-H,h.265,h.264
video-bitrate = 
video-crf = 
video-max-width = 
h264-max-level = 5.1
use-qsv-decoder-with-encoder = True
ios-audio = True
ios-first-track-only = False
ios-audio-filter = 
max-audio-channels = 
audio-codec = ac3,eac3
audio-language = eng
audio-default-language = eng
audio-channel-bitrate = 
audio-filter = 
subtitle-codec = srt
subtitle-language = eng
subtitle-default-language = eng
subtitle-encoding = 
fullpathguess = False
convert-mp4 = False
tagfile = True
tag-language = en
download-artwork = Poster
download-subs = True
embed-subs = False
sub-providers = addic7ed,podnapisi,thesubdb,opensubtitles
permissions = 0777
post-process = False
pix-fmt = 
aac_adtstoasc = False
postopts = 
preopts =

**Comment by Collisionc** [comment] 2017-04-14 02:28
Check what is running when cpu usage is at 5%. If it's sitting on ffprobe.exe and you are using a version of ffmpeg that was released in the last 2~ weeks, then it's due to a bug in ffprobe/ffmpeg that was resolved here - https://github.com/FFmpeg/FFmpeg/commit/1f9419753667beb6298d8d8b683211680abb4fe6

Downloading/compiling a build that was built in the last 24-36~ hours will fix it.

**Comment by mdhiggins** [comment] 2017-04-14 02:33
Need more information

What codecs were actively being transcoded? What encoders were you using? Was any remuxing taking place causing disk write speed limitations as bottle neck?

From: justinglock40
Sent: Thursday, April 13, 2017 6:46 PM
To: mdhiggins/sickbeard_mp4_automator
Cc: Subscribed
Subject: [mdhiggins/sickbeard_mp4_automator] Help! Script performance in gimpmode (#718)

So my issue is that the script is working as designed. However, on my Dual E5-2660 Xeon (16 core, 32 threads, approx. 17,000 passmark) is not breaking 5% utilization and I can not for the life of me figure out why it's gimped.

Also here are my autoProcess settings if this can help at all:
[MP4]
ffmpeg = C:\ffmpeg\bin\ffmpeg.exe
ffprobe = C:\ffmpeg\bin\ffprobe.exe
threads = auto
output_directory =
copy_to =
move_to =
output_extension = mp4
output_format = mp4
delete_original = True
relocate_moov = True
video-codec = h264,x264,hevc,h265,x265,HEVC,mpeg4,MPEG-4,MPEG-H,h.265,h.264
video-bitrate =
video-crf =
video-max-width =
h264-max-level = 5.1
use-qsv-decoder-with-encoder = True
ios-audio = True
ios-first-track-only = False
ios-audio-filter =
max-audio-channels =
audio-codec = ac3,eac3
audio-language = eng
audio-default-language = eng
audio-channel-bitrate =
audio-filter =
subtitle-codec = srt
subtitle-language = eng
subtitle-default-language = eng
subtitle-encoding =
fullpathguess = False
convert-mp4 = False
tagfile = True
tag-language = en
download-artwork = Poster
download-subs = True
embed-subs = False
sub-providers = addic7ed,podnapisi,thesubdb,opensubtitles
permissions = 0777
post-process = False
pix-fmt =
aac_adtstoasc = False
postopts =
preopts =

**Comment by justinglock40** [comment] 2017-04-14 02:40
I'm not sure as to what codec was running. and I get my ffmpeg last night the static windows build

**Comment by mdhiggins** [comment] 2017-04-14 02:42
Some codecs do not support multi threading

In many cases the cpu isn’t doing anything and FFMPEG is just copying the steam from one container to another and your HDD write speeds are the rate limiting step. These are just some of the reasons you may notice little CPU utilization. It would be critical to determine what encoders were running (H264, H265, libx264, etc, aac, libfdkaac, etc) as well as HDD write speed utilization

**Comment by Collisionc** [comment] 2017-04-14 02:45
Check if ffprobe.exe is running in your task manager when this occurs.  I had this very same issue for the last few days and it drove me crazy.

**Comment by justinglock40** [comment] 2017-04-14 02:55
It seems to have resolved itself I did some windows updates and rebooted and it seems to be scurrying  along now. I'll see if it happens again to be sure. and check FFprobe.

The disk is and SSD on SATA3 so I doubt that's the limiting factor?

**Comment by mdhiggins** [comment] 2017-04-14 09:38
Probably not the SSD then. Probably encoder limited maybe the audio encoder. Or maybe just a random FFMPEG bug if it resolved with a reboot.

**Closed** 2017-04-14 09:39 UTC
