### ISSUE TITLE
Problem getting sickbeard_mp4_automator to work with Sickrage and Deluge

### ISSUE THREAD

**Issue by OskarPersson** [mdhiggins/sickbeard_mp4_automator#228] opened 2015-04-03 12:43 UTC
I'm trying to setup the [sickbeard_mp4_automator (SMA)](https://github.com/mdhiggins/sickbeard_mp4_automator/) with [SickRage](https://github.com/SiCKRAGETV/SickRage) and [Deluge](http://dev.deluge-torrent.org/wiki/UserGuide/ThinClient) on my Windows 8.1 machine.

I've managed to get Sickrage to send new torrents to Deluge but I can't get the SMA to work. When Deluge finishes a download I can see a CMD window open and close (too fast to see what it says) and then nothing more.

I'm not sure if I really understand how to use it, am I supposed to install the SMA or just have the source files in a directory and change the config file?

Is it some file I should run to start the SMA or is Sickrage or Deluge supposed to start it automatically?

* [Sickrage config.ini](http://pastebin.com/NRtHRhgx)
* [SMA autoProcess.ini](http://pastebin.com/093jWgfq)

**Comment by mdhiggins** [comment] 2015-04-03 13:07
You need to follow the instructions in the Deluge Daemon section of the readme to configure deluge to pass files back to SickRage, otherwise nothing will happen when the downloads complete.

See here:
https://github.com/mdhiggins/sickbeard_mp4_automator#deluge-daemon

**Comment by OskarPersson** [comment] 2015-04-03 13:15
Yes I also think that the problem has something to do with that, though I'm unsure what I should change in my autoProcess.ini file that I linked above. Have I written it under the correct section? I couldn't find a Deluge section in the sample file.

And the ffmpeg && ffproble paths, should there be `\\` or `\` in the path?

**Comment by mdhiggins** [comment] 2015-04-03 13:20
My mistake I missed the part where you said you have the CMD window popping up.

Single `\` is fine in the autoProcess.ini file.

I would check your info.log file in the script directory and see if the delugePostProcess script has put out any logs that might be helpful. Feel free to post them and I'll take a look. Additionally you can verify the script is working by testing with manual.py. If manual.py works then your autoPrcoess.ini stuff is likely fine, and the problem is with deluge executing things.

My flex server is running on Windows as well, here is a screenshot of what my deluge execute plugin settings looks like:

![screen shot 2015-04-03 at 9 19 08 am](https://cloud.githubusercontent.com/assets/3608298/6982644/933fcf42-d9e2-11e4-98f0-3c633616320c.png)

**Comment by mdhiggins** [comment] 2015-04-03 13:24
Also I corrected the deluge section of the autoProcess.ini.sample. Additionally, if you run manual.py, it will automatically add any missing settings and their default values to the autoProcess.ini

**Comment by OskarPersson** [comment] 2015-04-03 13:39
Where is the script directory with the info.log file located?

**Comment by OskarPersson** [comment] 2015-04-03 13:59
I tried using manual.py but it didn't work.

```
No handlers could be found for logger "readSettings"
64
File 'C:\Modern.Family.S06E19.mkv' is not in the correct format
```

**Comment by mdhiggins** [comment] 2015-04-03 15:46
This was my fault, I found the problem. There was a pull request I recently merged to update guessit that for some reason reverted manual.py back to a really old version and created problems. It should be fixed now. Try manual.py again and report back. Sorry about that.

**Comment by OskarPersson** [comment] 2015-04-03 15:56
Hmm, I tried the new one and it generates a log file containing
```
2015-04-03 17:53:30 - MANUAL - INFO - Manual processor started.
2015-04-03 17:53:30 - MANUAL - WARNING - Audio bitrate was invalid, defaulting to 256 per channel.
```

In cmd it says

```
Manual processor started.
Audio bitrate was invalid, defaulting to 256 per channel.
64bit Python
File 'C:\Modern.Family.S06E19.mkv' is not in the correct format
```

**Comment by mdhiggins** [comment] 2015-04-03 15:58
Hm not sure why its saying its in the incorrect format, perhaps there's something up with the path. I'd recommend launch manual.py without any command line options.

When it prompts you for the file just drag the file into the command prompt and press enter. Then let it guess (it should work) and proceed from there. Let me know if that lets it process the file. And now that the logging is working try running something through deluge and see if anything shows up for delugePostProcess.

**Comment by OskarPersson** [comment] 2015-04-03 16:03
Tried the drag and drop, didn't work either.
![skarmavbild 2015-04-03 kl 18 02 23](https://cloud.githubusercontent.com/assets/935414/6984685/b74060ca-da2b-11e4-9df4-1020241c28fe.png)

**Comment by mdhiggins** [comment] 2015-04-03 16:07
Looks like you're missing the stevedore module. Installing subliminal includes this, but if you don't want subliminal, you can do a

`pip install stevedore`

If you don't know how to do pip installs, let me know and I'll walk you through it.

**Comment by OskarPersson** [comment] 2015-04-03 17:12
I installed subliminal and running manual.py now works! Though when downloading using SickRage and Deluge the CMD window still just opens and then closes and nothing more happens. What should happen? Should a windows appear and show the progress of the conversion or does it all happen in the background and I should wait for a .mp4 file to appear?

**Comment by mdhiggins** [comment] 2015-04-03 19:05
It happens in the background mostly but you should see delugePostProcess appear in the info.log file. One option to make sure you're not having some random error executing the script is to edit the batch file and add `pause` as the last line of the bat file. That might help if the log isn't useful. 



—

**Comment by OskarPersson** [comment] 2015-04-04 00:07
Apparently gevent wasn't installed correctly so I fixed that.

Now when the deluge download is done I get this in info.log

```
2015-04-04 01:43:37 - delugePostProcess - INFO - Deluge post processing started.
2015-04-04 01:43:37 - readSettings - WARNING - Audio bitrate was invalid, defaulting to 256 per channel.
```
but there is no file created.

I tried adding `pause` to the last line of the .bat file but then there is just a empty cmd window open and nothing more happens.

**Comment by mdhiggins** [comment] 2015-04-04 03:53
Alright you can put the batch file back to how it was. If delugePostProcess is showing up in the log that means its benign executed. Was there any additional information in the log file after that point than what you posted?

**Comment by OskarPersson** [comment] 2015-04-04 10:47
Nope, just those two lines

**Comment by OskarPersson** [comment] 2015-04-04 12:41
I think I actually got it working now! Some settings in Sickrage hadn't been saved (think I missed some of them entirely). Also I changed some of the folders that Sickrage and Deluge work with.

Thanks for all your help! :D

**Comment by mdhiggins** [comment] 2015-04-04 19:53
Glad everything is working! Gonna close this then. Thanks

**Closed by mdhiggins** 2015-04-04 19:53 UTC
